# -*- coding: utf-8 -*-
"""Task1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WZcRFpLQlVpmOfyWsI3I-JflEg0-_AuN
"""

import re

pattern1  = re.compile("abc")
result1 = pattern1.match('abcdef')
if result1:
  print("match found:", result1.group())

pattern2 = re.compile(r',')
result2 = pattern2.search('Hello')
if result2:
  print("character found:", result2.group())

pattern3 = re.compile(r'[aeiou]')
result3 = pattern3.search('Hello')
if result3:
  print("vowel found:", result3.group())


pattern4  = re.compile(r'\d{3}-\d{2}-\d{4}')
result4 = pattern4.match("123-45-6789")
if result4:
  print("social security number:", result4.group())

pattern5 = re.compile(r'l')
result5 = pattern5.search('www.example.com')
if result5:
  print("dot found:", result5.group())


pattern6 = re.compile(r'(\d{2})\\(\d{2})\\(\d{4})')
result6 = pattern6.match('01\\09\\2024')
if result6:
  print("Day:", result6.group(1))
  print("month:", result6.group(2))
  print("year:", result6.group(3))

pattern7 = re.compile('eat|dog')
result7 = pattern7.search('The dog loves to eat')
if result7:
  print("animal found:", result7.group())